### ISSUE TITLE
Plugin not working on iOS devices.

### ISSUE THREAD

**Issue by Aishwarya-Karandikar-DFT** [Amphiluke/cordova-plugin-save-dialog#6]
Hi,
We are unable to save file using this plugin on iOS devices : 
1.Iphone - version 15
2. iPad - version 15 & 16.

Is there any way to fix this issue?

**Comment by Amphiluke** [comment]
Hello,

I have checked on real iPhone (iOS 15.8.2) but found no issues. Could you provide some details on the problem you have faced? Please check Xcode debug logs as well as output of Web Inspector in Safari.

**Comment by Aishwarya-Karandikar-DFT** [comment]
Hi, thanks for your reply. When I rechecked today, it's working as expected.
